<a href="https://colab.research.google.com/github/prathicc/Pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to tensors

### Creating tensors

Pytorch tensors are created using 'torch.tensor()'
https://pytorch.org/docs/stable/tensors.html

Scalars and Vectors are lower case, MATRIX and TENSORS are upper case

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# give back python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #count the number of pairs of square brackets

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0][1]

tensor(8)

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [ ]:
TENSOR[0][0][1]

tensor(2)

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# doesnt work
# TENSOR = torch.tensor([[[1,2,3],
#                         [3,6,9],
#                         [2,5,4]],
#                        [[11,12,13],
#                        [14,15,16]]])
# TENSOR

In [ ]:
# doesnt work
# TENSOR = torch.tensor([[[1,2,3],
#                         [3,6,9],
#                         [2,5,4]],
#                        [[11,12,13],
#                        [14,15,16],
#                         [14,15]]])
# TENSOR

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]],
                       [[11,12,13],
                       [14,15,16],
                        [14,15,16]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  5,  4]],

        [[11, 12, 13],
         [14, 15, 16],
         [14, 15, 16]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape # we have two 3x3 tensors

torch.Size([2, 3, 3])

In [ ]:
T = torch.tensor([[[[
                    [
                      [[1,2],
                       [1,2]],
                      [[3,4],
                       [5,6]]
                      ],
                     [
                      [[1,2],
                       [1,2]],
                      [[3,4],
                       [5,6]]
                      ]
                     ]]]])

In [ ]:
print(T.ndim)
print(T.shape)

7
torch.Size([1, 1, 1, 2, 2, 2, 2])


### Random tensors
Why random tensors?
Random tensors are important because the way many neural netwroks work is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with raandom numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
# Create random tensor of size/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0505, 0.6659, 0.4009, 0.8884],
        [0.2193, 0.7124, 0.4731, 0.3407],
        [0.3962, 0.8652, 0.0603, 0.8768]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a rondom tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeors and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# use torch.range()

In [ ]:
torch.range(0,10)

<ipython-input-54-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#ues this instead
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start = 0,end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0,],
                               dtype = None,
                               device = 'cpu',
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
# Int 64 tensor
int_64_tensor = torch.tensor([3,6,9],
                               dtype = None)
int_64_tensor.dtype

torch.int64

In [ ]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0,6.0,9.0,],
                               dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
# or
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. tensor.dtype
2. tensor.shape
3. tensor.device

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])

In [ ]:
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix Multiplication

Two two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [ ]:
# Element wise multiplication
print(f"{tensor} * {tensor} is: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) is:  tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

Vectorization

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.69 ms, sys: 0 ns, total: 1.69 ms
Wall time: 3.78 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 89 µs, sys: 0 ns, total: 89 µs
Wall time: 93.5 µs


tensor(14)

### Shape errors

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
torch.mm(tensor_A, tensor_B.T) # alias for matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of our tensors using a transpose. A transpose switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
tensor_A @ tensor_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_A.T @ tensor_B

tensor([[ 76, 103],
        [100, 136]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean (doesnt work)
# torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# reuturns index
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# add an extra dimension
x.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
# Change the view
x.view(1,9)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x[0] = 100

In [ ]:
z[0]

tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])

In [ ]:
# changing z changes x (as view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x]) # takes a list of tensors
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim = 1) # takes a list of tensors
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x = x.reshape(1,9)

In [ ]:
# squeeze - removes all single dimensions from a target tensor
x.shape, torch.squeeze(x).shape

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
x.squeeze().shape

torch.Size([2, 2, 2])

In [ ]:
x = torch.arange(1, 11)

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
x_squeezed = x.squeeze()
print(f"previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}, {x_unsqueezed.shape}")

previous target: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous shape: torch.Size([10])

New tensor: tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
x_squeezed = x.squeeze()
print(f"previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed}, {x_unsqueezed.shape}")

previous target: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous shape: torch.Size([10])

New tensor: tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]), torch.Size([10, 1])


In [ ]:
# torch.permute() rearranges the dimesions of a target in a specified order
# returns a view
x = torch.randn(2,3,5)
print(x.size())
torch.permute(x, (2,0,1)).size()

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [ ]:
print(x)
print(x.permute([2,0,1]))

tensor([[[-1.0303, -0.7661, -1.1985, -1.4965, -1.1933],
         [-0.2638, -1.3588, -1.4903, -0.2265,  1.0045],
         [-0.0266,  0.9960,  0.1786,  0.2862,  0.4330]],

        [[-0.4316, -0.1971,  0.9631, -1.0105, -1.0305],
         [-1.1533, -0.7851, -0.8150,  0.2134, -1.3139],
         [-1.2170, -0.9368, -0.2791, -0.3181,  2.8038]]])
tensor([[[-1.0303, -0.2638, -0.0266],
         [-0.4316, -1.1533, -1.2170]],

        [[-0.7661, -1.3588,  0.9960],
         [-0.1971, -0.7851, -0.9368]],

        [[-1.1985, -1.4903,  0.1786],
         [ 0.9631, -0.8150, -0.2791]],

        [[-1.4965, -0.2265,  0.2862],
         [-1.0105,  0.2134, -0.3181]],

        [[-1.1933,  1.0045,  0.4330],
         [-1.0305, -1.3139,  2.8038]]])


In [ ]:
x_original = torch.randn((224,224,3))
x_original.permute([2,1,0]).shape

torch.Size([3, 224, 224])

In [ ]:
x_original.permute(2, 0, 1).shape

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)



In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0,0] #same

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
# You can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0,2,2]
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## Pytorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Tensor to NumPy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: pytorch reflects numpys default datatye float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

## Reproducibility (trying to take random out of random)

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

sometimes you'd like there to be a little less randomness to perform repeatable experiments

To reduce randomness comes the concept of ** random seed **.

What random seed does is "flavour" the randomness.

In [ ]:
import torch

A = torch.rand(3,4)
B = torch.rand(3,4)

print(A)
print(B)
print(A==B)

tensor([[0.6755, 0.5888, 0.5385, 0.1956],
        [0.5140, 0.6952, 0.4197, 0.2485],
        [0.3092, 0.2891, 0.3114, 0.9047]])
tensor([[0.2116, 0.6973, 0.7328, 0.6935],
        [0.3312, 0.9122, 0.1843, 0.6460],
        [0.5678, 0.8909, 0.2076, 0.2998]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

D = torch.rand(3,4)
print(C)
print(D)
print(C==D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch


###1. Getting a GPU

1. Googe Colab
2. Own GPU
3. Use cloud computing - GCP, AWS, Azure


### 2. Check for GPU access with Pytorch

In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count number of GPUs
torch.cuda.device_count()

0

Since pytorch is capable of running compute on the GPU or CPU, its best
practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else CPU

### 3. Putting tensors and models on the GPU

faster computations

In [ ]:
# Create a tensor (default is CPU)
tensor = torch.tensor([1,2,3])

print(tensor, tensor,device)

tensor([1, 2, 3]) tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the cpu

In [ ]:
# if tenosr is on GPU can't transform it to numpy
tensor_on_gpu.numpy() # top 3 errors

In [ ]:
# fixing
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

## Exercise

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises


In [ ]:
# Create a random tensor with shape (7, 7).
A = torch.rand(7,7)

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
B = torch.rand(1,7)
print(B)
A @ B.T

tensor([[0.6099, 0.5643, 0.0594, 0.7099, 0.4250, 0.2709, 0.9295]])


tensor([[1.5895],
        [1.6761],
        [1.4914],
        [1.3595],
        [1.0976],
        [1.1914],
        [1.0589]])

In [ ]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
A = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
B = torch.rand(1,7)
A @ B.T

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [ ]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [ ]:
!nvidia-smi

Thu Jul 11 06:02:31 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
import torch
torch.manual_seed(1234)
A = torch.rand(2,3, device = 'cuda')
B = torch.rand(2,3, device = 'cuda')

In [ ]:
#Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
C = A @ B.T
C

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [ ]:
# Find the maximum and minimum values of the output of 7.
print(torch.max(C))
print(torch.min(C))

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


In [ ]:
# Find the maximum and minimum index values of the output of 7.
print(torch.argmax(C))
print(torch.argmin(C))

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')


In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left
# with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
import torch
torch.manual_seed(7)
D = torch.rand(1,1,1,10)
E = torch.squeeze(D)
print(D, D.shape)
print(E, E.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
